import type { Metadata } from "next";
import { Open_Sans, Geist_Mono } from "next/font/google";
import "../globals.css";
import Providers from "../providers";
import { auth } from "@/auth";

import { getDictionary, Locale } from "./dictionaries";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
<<<<<<< ours
  const session = await auth();
  const dictionary = await getDictionary(lang);

||||||| ancestor

=======
>>>>>>> theirs
  return (
    <html
      lang={lang}
      className={`${openSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className={`${openSans.className} min-h-full flex flex-col`}>
        <Providers session={session} dictionary={dictionary}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
